---
- name: NextCloud
  hosts: web-server

  tasks:
    - name: Timezone settings
      community.general.timezone:
        name: Europe/Moscow
    - name: Upgrade Software
      ansible.builtin.apt:
        upgrade: "yes"
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - apache2
          - acl
          - libapache2-mod-php
          - php-curl
          - php-gd
          - php-json
          - php-mbstring
          - php-xml
          - php-zip
          - php-pgsql
          - postgresql-all
          - bzip2
          - python3-pip
        state: present
    - name: Install Python packages
      ansible.builtin.pip:
        break_system_packages: true
        name: psycopg2
    - name: Download and unpack NextCloud
      ansible.builtin.unarchive:
        dest: "/var/www/html"
        src: "https://download.nextcloud.com/server/releases/latest-30.tar.bz2"
        remote_src: true
        owner: "www-data"
        group: "www-data"
        creates: "/var/www/html/nextcloud"
    - name: PostgreSQL user
      become: true
      become_user: postgres
      community.postgresql.postgresql_user:
        name: dbuser
        password: dbpassword
    - name: PostgreSQL DB
      become: true
      become_user: postgres
      community.postgresql.postgresql_db:
        name: dbnextcloud
        owner: dbuser